# Generated by Django 4.2.4 on 2023-09-19 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customer_service_type_pqrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service',
            name='priority',
            field=models.CharField(choices=[('Media', 'Media'), ('Alta', 'Alta'), ('Baja', 'Baja')], max_length=100, verbose_name='Prioridad PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Primera Vez', 'Primera Vez'), ('Consulta', 'Consulta'), ('Seguimiento', 'Seguimiento')], max_length=100, verbose_name='Tipo de cita'),
        ),
    ]
