# Generated by Django 4.2.4 on 2023-09-23 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customer_service_priority_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer_service',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Sugerencia', 'Sugerencia'), ('Reclamo', 'Reclamo'), ('Queja', 'Queja')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Primera Vez', 'Primera Vez'), ('Seguimiento', 'Seguimiento'), ('Consulta', 'Consulta')], max_length=100, verbose_name='Tipo de cita'),
        ),
    ]
