# Generated by Django 4.2.4 on 2023-09-23 19:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0008_customer_service_respondido_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_service',
            name='number_phone',
        ),
        migrations.AddField(
            model_name='customer_service',
            name='email',
            field=models.EmailField(max_length=100, null=True, verbose_name='Correo electronico'),
        ),
        migrations.AddField(
            model_name='customer_service',
            name='usuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Reclamo', 'Reclamo'), ('Queja', 'Queja'), ('Sugerencia', 'Sugerencia'), ('Peticion', 'Peticion')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Primera Vez', 'Primera Vez'), ('Consulta', 'Consulta'), ('Seguimiento', 'Seguimiento')], max_length=100, verbose_name='Tipo de cita'),
        ),
    ]
