# Generated by Django 4.2.4 on 2023-09-24 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_remove_customer_service_usuario_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rendezvous',
            name='respondido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Queja', 'Queja'), ('Peticion', 'Peticion'), ('Sugerencia', 'Sugerencia'), ('Reclamo', 'Reclamo')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Primera Vez', 'Primera Vez'), ('Seguimiento', 'Seguimiento')], max_length=100, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='virtual_onsite',
            field=models.CharField(choices=[('Virtual', 'Virtual'), ('Presencial', 'Presencial')], max_length=100, verbose_name='Virtual o presencial'),
        ),
    ]
