# Generated by Django 4.2.4 on 2023-09-25 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_customer_service_type_pqrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia'), ('Queja', 'Queja')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Seguimiento', 'Seguimiento'), ('Consulta', 'Consulta'), ('Primera Vez', 'Primera Vez')], max_length=100, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='virtual_onsite',
            field=models.CharField(choices=[('Presencial', 'Presencial'), ('Virtual', 'Virtual')], max_length=100, verbose_name='Virtual o presencial'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta ', 'Tarjeta ')], max_length=100, verbose_name='Metodo de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_value',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor unitario'),
        ),
    ]
