# Generated by Django 4.2.4 on 2023-09-25 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_customer_service_type_pqrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia'), ('Queja', 'Queja'), ('Peticion', 'Peticion')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Tarjeta ', 'Tarjeta '), ('Efectivo', 'Efectivo')], max_length=100, verbose_name='Metodo de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_value',
            field=models.DecimalField(decimal_places=8, max_digits=10, verbose_name='Valor unitario'),
        ),
    ]
