# Generated by Django 4.2.4 on 2023-09-25 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_alter_customer_service_type_pqrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Seguimiento', 'Seguimiento'), ('Primera Vez', 'Primera Vez'), ('Consulta', 'Consulta')], max_length=100, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta ', 'Tarjeta ')], max_length=100, verbose_name='Metodo de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_value',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Valor unitario'),
        ),
    ]
