# Generated by Django 4.2.4 on 2023-09-25 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_rendezvous_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Primera Vez', 'Primera Vez'), ('Consulta', 'Consulta'), ('Seguimiento', 'Seguimiento')], max_length=100, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Tarjeta ', 'Tarjeta '), ('Efectivo', 'Efectivo')], max_length=100, verbose_name='Metodo de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_value',
            field=models.DecimalField(decimal_places=0, max_digits=12, verbose_name='Valor total'),
        ),
    ]
