# Generated by Django 4.2.4 on 2023-09-25 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_rendezvous_appointment_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Queja', 'Queja'), ('Peticion', 'Peticion'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Seguimiento', 'Seguimiento'), ('Primera Vez', 'Primera Vez'), ('Consulta', 'Consulta')], max_length=100, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Efectivo', 'Efectivo'), ('Tarjeta ', 'Tarjeta ')], max_length=100, verbose_name='Metodo de pago'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='total_value',
            field=models.FloatField(verbose_name='Valor total'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='unit_value',
            field=models.FloatField(verbose_name='Valor unitario'),
        ),
    ]
