# Generated by Django 4.2.4 on 2023-10-05 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_customer_service_prioridad_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer_service',
            old_name='respondido',
            new_name='respuest',
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Sugerencia', 'Sugerencia'), ('Reclamo', 'Reclamo'), ('Queja', 'Queja')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Consulta', 'Consulta'), ('Seguimiento', 'Seguimiento'), ('Primera Vez', 'Primera Vez')], max_length=100, verbose_name='Tipo de cita'),
        ),
    ]
