# Generated by Django 4.2.4 on 2023-10-10 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_alter_customer_service_type_pqrs_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service',
            name='Prioridad',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Alta', 'Alta'), ('Media', 'Media')], max_length=100, verbose_name='Prioridad PQRS'),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='respuest',
            field=models.CharField(choices=[('NO', 'NO'), ('SI', 'SI')], max_length=100, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Queja', 'Queja'), ('Sugerencia', 'Sugerencia'), ('Reclamo', 'Reclamo')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Seguimiento', 'Seguimiento'), ('Primera Vez', 'Primera Vez'), ('Consulta', 'Consulta')], max_length=100, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='sale',
            name='payment_method',
            field=models.CharField(choices=[('Tarjeta ', 'Tarjeta '), ('Efectivo', 'Efectivo')], max_length=100, verbose_name='Metodo de pago'),
        ),
    ]
