# Generated by Django 4.2.4 on 2023-10-12 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_alter_customer_service_prioridad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer_service',
            name='Prioridad',
            field=models.CharField(choices=[('Alta', 'Alta'), ('Media', 'Media'), ('Baja', 'Baja')], max_length=100, verbose_name='Prioridad PQRS'),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Reclamo', 'Reclamo'), ('Peticion', 'Peticion'), ('Sugerencia', 'Sugerencia'), ('Queja', 'Queja')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Primera Vez', 'Primera Vez'), ('Seguimiento', 'Seguimiento'), ('Consulta', 'Consulta')], max_length=100, verbose_name='Tipo de cita'),
        ),
    ]
