# Generated by Django 4.2.4 on 2023-10-12 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_alter_customer_service_prioridad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer_service',
            name='Prioridad',
        ),
        migrations.AddField(
            model_name='customer_service',
            name='Priority',
            field=models.CharField(choices=[('Baja', 'Baja'), ('Alta', 'Alta'), ('Media', 'Media')], default='', max_length=100, verbose_name='Prioridad PQRS'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='respuest',
            field=models.CharField(choices=[('NO RESPONDIDO', 'NO RESPONDIDO'), ('RESPONDIDO', 'RESPONDIDO')], max_length=100, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='customer_service',
            name='type_pqrs',
            field=models.CharField(choices=[('Peticion', 'Peticion'), ('Reclamo', 'Reclamo'), ('Sugerencia', 'Sugerencia'), ('Queja', 'Queja')], max_length=100, verbose_name='Tipo PQRS'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='appointment_type',
            field=models.CharField(choices=[('Seguimiento', 'Seguimiento'), ('Primera Vez', 'Primera Vez'), ('Consulta', 'Consulta')], max_length=100, verbose_name='Tipo de cita'),
        ),
        migrations.AlterField(
            model_name='rendezvous',
            name='location',
            field=models.CharField(choices=[('VIRTUAL', 'VIRTUAL'), ('Calle 31a #16-23', 'Calle 31a #16-23')], max_length=100, verbose_name='Ubicacion'),
        ),
    ]
